services:
  playground-node:
    container_name: 'node'
    hostname: 'node'
    user: $UID:$GID
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
      dockerfile: Dockerfile
    restart: always
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace